[package]
name = "best_cfb_divisions"
version = "0.1.0"
edition = "2021"

[dependencies]
fxhash = "0.2.1"
itertools = "0.10.5"
rand = "0.8.5"
rayon = "1.5.3"
# reqwest = { version = "0.11", features = ["blocking", "json"] }
# serde_json = "1.0.85"

[profile.release]
lto = true
panic = "abort"
