use std::collections::HashMap;

use crate::types::TeamPair;

#[macro_export]
macro_rules! collection {
  // map-like
  ($($k:expr => $v:expr),* $(,)?) => {{
      core::convert::From::from([$(($k, $v),)*])
  }};
}

pub fn create_lookup_table() -> HashMap<TeamPair, u32> {
    collection! {
      ("Indiana", "Michigan State") => 305,
      ("Indiana", "Northwestern") => 249,
      ("Indiana", "Ohio State") => 224,
      ("Indiana", "Penn State") => 604,
      ("Indiana", "Purdue") => 114,
      ("Indiana", "Rutgers") => 734,
      ("Indiana", "UCLA") => 2042,
      ("Indiana", "Illinois") => 151,
      ("Indiana", "Iowa") => 395,
      ("Indiana", "Maryland") => 637,
      ("Indiana", "Michigan") => 315,
      ("Indiana", "Minnesota") => 635,
      ("Indiana", "Nebraska") => 658,
      ("Indiana", "USC") => 2054,
      ("Indiana", "Wisconsin") => 376,
      ("Michigan State", "Northwestern") => 239,
      ("Michigan State", "Ohio State") => 247,
      ("Michigan State", "Penn State") => 496,
      ("Michigan State", "Purdue") => 248,
      ("Michigan State", "Rutgers") => 666,
      ("Michigan State", "UCLA") => 2212,
      ("Michigan State", "Illinois") => 321,
      ("Michigan State", "Iowa") => 429,
      ("Michigan State", "Maryland") => 599,
      ("Michigan State", "Michigan") => 64,
      ("Michigan State", "Minnesota") => 625,
      ("Michigan State", "Nebraska") => 726,
      ("Michigan State", "USC") => 2224,
      ("Michigan State", "Wisconsin") => 366,
      ("Northwestern", "Ohio State") => 377,
      ("Northwestern", "Penn State") => 628,
      ("Northwestern", "Purdue") => 142,
      ("Northwestern", "Rutgers") => 798,
      ("Northwestern", "UCLA") => 2017,
      ("Northwestern", "Illinois") => 154,
      ("Northwestern", "Iowa") => 233,
      ("Northwestern", "Maryland") => 731,
      ("Northwestern", "Michigan") => 262,
      ("Northwestern", "Minnesota") => 408,
      ("Northwestern", "Nebraska") => 531,
      ("Northwestern", "USC") => 2029,
      ("Northwestern", "Wisconsin") => 145,
      ("Ohio State", "Penn State") => 380,
      ("Ohio State", "Purdue") => 242,
      ("Ohio State", "Rutgers") => 514,
      ("Ohio State", "UCLA") => 2236,
      ("Ohio State", "Illinois") => 294,
      ("Ohio State", "Iowa") => 539,
      ("Ohio State", "Maryland") => 416,
      ("Ohio State", "Michigan") => 184,
      ("Ohio State", "Minnesota") => 763,
      ("Ohio State", "Nebraska") => 837,
      ("Ohio State", "USC") => 2248,
      ("Ohio State", "Wisconsin") => 504,
      ("Penn State", "Purdue") => 578,
      ("Penn State", "Rutgers") => 190,
      ("Penn State", "UCLA") => 2599,
      ("Penn State", "Illinois") => 669,
      ("Penn State", "Iowa") => 815,
      ("Penn State", "Maryland") => 201,
      ("Penn State", "Michigan") => 429,
      ("Penn State", "Minnesota") => 1011,
      ("Penn State", "Nebraska") => 1112,
      ("Penn State", "USC") => 2611,
      ("Penn State", "Wisconsin") => 752,
      ("Purdue", "Rutgers") => 750,
      ("Purdue", "UCLA") => 2085,
      ("Purdue", "Illinois") => 90,
      ("Purdue", "Iowa") => 326,
      ("Purdue", "Maryland") => 652,
      ("Purdue", "Michigan") => 259,
      ("Purdue", "Minnesota") => 528,
      ("Purdue", "Nebraska") => 624,
      ("Purdue", "USC") => 2097,
      ("Purdue", "Wisconsin") => 270,
      ("Rutgers", "Illinois") => 803,
      ("Rutgers", "Iowa") => 998,
      ("Rutgers", "Maryland") => 179,
      ("Rutgers", "Michigan") => 612,
      ("Rutgers", "Minnesota") => 1194,
      ("Rutgers", "Nebraska") => 1296,
      ("Rutgers", "USC") => 2757,
      ("Rutgers", "Wisconsin") => 935,
      ("UCLA", "Rutgers") => 2745,
      ("UCLA", "Illinois") => 1991,
      ("UCLA", "Iowa") => 1788,
      ("UCLA", "Maryland") => 2648,
      ("UCLA", "Michigan") => 2235,
      ("UCLA", "Minnesota") => 1920,
      ("UCLA", "Nebraska") => 1491,
      ("UCLA", "USC") => 14,
      ("UCLA", "Wisconsin") => 1959,
      ("Illinois", "Iowa") => 247,
      ("Illinois", "Maryland") => 708,
      ("Illinois", "Michigan") => 344,
      ("Illinois", "Minnesota") => 511,
      ("Illinois", "Nebraska") => 519,
      ("Illinois", "USC") => 2004,
      ("Illinois", "Wisconsin") => 252,
      ("Iowa", "Maryland") => 921,
      ("Iowa", "Michigan") => 451,
      ("Iowa", "Minnesota") => 303,
      ("Iowa", "Nebraska") => 303,
      ("Iowa", "USC") => 1801,
      ("Iowa", "Wisconsin") => 190,
      ("Maryland", "Michigan") => 537,
      ("Maryland", "Minnesota") => 1118,
      ("Maryland", "Nebraska") => 1220,
      ("Maryland", "USC") => 2663,
      ("Maryland", "Wisconsin") => 860,
      ("Michigan", "Minnesota") => 648,
      ("Michigan", "Nebraska") => 749,
      ("Michigan", "USC") => 2247,
      ("Michigan", "Wisconsin") => 389,
      ("Minnesota", "Nebraska") => 434,
      ("Minnesota", "USC") => 1932,
      ("Minnesota", "Wisconsin") => 266,
      ("Nebraska", "USC") => 1506,
      ("Nebraska", "Wisconsin") => 472,
      ("USC", "Wisconsin") => 1970,
    }
}
