use std::collections::HashMap;

use crate::types::TeamPair;

macro_rules! collection {
  // map-like
  ($($k:expr => $v:expr),* $(,)?) => {{
      core::convert::From::from([$(($k, $v),)*])
  }};
}

pub fn create_lookup_table() -> HashMap<TeamPair, u32> {
    collection! {
    ("Indiana University", "Michigan State University") => 305,
    ("Indiana University", "Northwestern University") => 249,
    ("Indiana University", "Ohio State University") => 224,
    ("Indiana University", "Pennsylvannia State University") => 604,
    ("Indiana University", "Purdue University") => 114,
    ("Indiana University", "Rutgers University") => 734,
    ("Indiana University", "University of California, Los Angles") => 2042,
    ("Indiana University", "University of Illinois") => 151,
    ("Indiana University", "University of Iowa") => 395,
    ("Indiana University", "University of Maryland") => 637,
    ("Indiana University", "University of Michigan") => 315,
    ("Indiana University", "University of Minnesota") => 635,
    ("Indiana University", "University of Nebraska") => 658,
    ("Indiana University", "University of Southern California") => 2054,
    ("Indiana University", "University of Wisconsin") => 376,
    ("Michigan State University", "Northwestern University") => 239,
    ("Michigan State University", "Ohio State University") => 247,
    ("Michigan State University", "Pennsylvannia State University") => 496,
    ("Michigan State University", "Purdue University") => 248,
    ("Michigan State University", "Rutgers University") => 666,
    ("Michigan State University", "University of California, Los Angles") => 2212,
    ("Michigan State University", "University of Illinois") => 321,
    ("Michigan State University", "University of Iowa") => 429,
    ("Michigan State University", "University of Maryland") => 599,
    ("Michigan State University", "University of Michigan") => 64,
    ("Michigan State University", "University of Minnesota") => 625,
    ("Michigan State University", "University of Nebraska") => 726,
    ("Michigan State University", "University of Southern California") => 2224,
    ("Michigan State University", "University of Wisconsin") => 366,
    ("Northwestern University", "Ohio State University") => 377,
    ("Northwestern University", "Pennsylvannia State University") => 628,
    ("Northwestern University", "Purdue University") => 142,
    ("Northwestern University", "Rutgers University") => 798,
    ("Northwestern University", "University of California, Los Angles") => 2017,
    ("Northwestern University", "University of Illinois") => 154,
    ("Northwestern University", "University of Iowa") => 233,
    ("Northwestern University", "University of Maryland") => 731,
    ("Northwestern University", "University of Michigan") => 262,
    ("Northwestern University", "University of Minnesota") => 408,
    ("Northwestern University", "University of Nebraska") => 531,
    ("Northwestern University", "University of Southern California") => 2029,
    ("Northwestern University", "University of Wisconsin") => 145,
    ("Ohio State University", "Pennsylvannia State University") => 380,
    ("Ohio State University", "Purdue University") => 242,
    ("Ohio State University", "Rutgers University") => 514,
    ("Ohio State University", "University of California, Los Angles") => 2236,
    ("Ohio State University", "University of Illinois") => 294,
    ("Ohio State University", "University of Iowa") => 539,
    ("Ohio State University", "University of Maryland") => 416,
    ("Ohio State University", "University of Michigan") => 184,
    ("Ohio State University", "University of Minnesota") => 763,
    ("Ohio State University", "University of Nebraska") => 837,
    ("Ohio State University", "University of Southern California") => 2248,
    ("Ohio State University", "University of Wisconsin") => 504,
    ("Pennsylvannia State University", "Purdue University") => 578,
    ("Pennsylvannia State University", "Rutgers University") => 190,
    ("Pennsylvannia State University", "University of California, Los Angles") => 2599,
    ("Pennsylvannia State University", "University of Illinois") => 669,
    ("Pennsylvannia State University", "University of Iowa") => 815,
    ("Pennsylvannia State University", "University of Maryland") => 201,
    ("Pennsylvannia State University", "University of Michigan") => 429,
    ("Pennsylvannia State University", "University of Minnesota") => 1011,
    ("Pennsylvannia State University", "University of Nebraska") => 1112,
    ("Pennsylvannia State University", "University of Southern California") => 2611,
    ("Pennsylvannia State University", "University of Wisconsin") => 752,
    ("Purdue University", "Rutgers University") => 750,
    ("Purdue University", "University of California, Los Angles") => 2085,
    ("Purdue University", "University of Illinois") => 90,
    ("Purdue University", "University of Iowa") => 326,
    ("Purdue University", "University of Maryland") => 652,
    ("Purdue University", "University of Michigan") => 259,
    ("Purdue University", "University of Minnesota") => 528,
    ("Purdue University", "University of Nebraska") => 624,
    ("Purdue University", "University of Southern California") => 2097,
    ("Purdue University", "University of Wisconsin") => 270,
    ("Rutgers University", "University of Illinois") => 803,
    ("Rutgers University", "University of Iowa") => 998,
    ("Rutgers University", "University of Maryland") => 179,
    ("Rutgers University", "University of Michigan") => 612,
    ("Rutgers University", "University of Minnesota") => 1194,
    ("Rutgers University", "University of Nebraska") => 1296,
    ("Rutgers University", "University of Southern California") => 2757,
    ("Rutgers University", "University of Wisconsin") => 935,
    ("University of California, Los Angles", "Rutgers University") => 2745,
    ("University of California, Los Angles", "University of Illinois") => 1991,
    ("University of California, Los Angles", "University of Iowa") => 1788,
    ("University of California, Los Angles", "University of Maryland") => 2648,
    ("University of California, Los Angles", "University of Michigan") => 2235,
    ("University of California, Los Angles", "University of Minnesota") => 1920,
    ("University of California, Los Angles", "University of Nebraska") => 1491,
    ("University of California, Los Angles", "University of Southern California") => 14,
    ("University of California, Los Angles", "University of Wisconsin") => 1959,
    ("University of Illinois", "University of Iowa") => 247,
    ("University of Illinois", "University of Maryland") => 708,
    ("University of Illinois", "University of Michigan") => 344,
    ("University of Illinois", "University of Minnesota") => 511,
    ("University of Illinois", "University of Nebraska") => 519,
    ("University of Illinois", "University of Southern California") => 2004,
    ("University of Illinois", "University of Wisconsin") => 252,
    ("University of Iowa", "University of Maryland") => 921,
    ("University of Iowa", "University of Michigan") => 451,
    ("University of Iowa", "University of Minnesota") => 303,
    ("University of Iowa", "University of Nebraska") => 303,
    ("University of Iowa", "University of Southern California") => 1801,
    ("University of Iowa", "University of Wisconsin") => 190,
    ("University of Maryland", "University of Michigan") => 537,
    ("University of Maryland", "University of Minnesota") => 1118,
    ("University of Maryland", "University of Nebraska") => 1220,
    ("University of Maryland", "University of Southern California") => 2663,
    ("University of Maryland", "University of Wisconsin") => 860,
    ("University of Michigan", "University of Minnesota") => 648,
    ("University of Michigan", "University of Nebraska") => 749,
    ("University of Michigan", "University of Southern California") => 2247,
    ("University of Michigan", "University of Wisconsin") => 389,
    ("University of Minnesota", "University of Nebraska") => 434,
    ("University of Minnesota", "University of Southern California") => 1932,
    ("University of Minnesota", "University of Wisconsin") => 266,
    ("University of Nebraska", "University of Southern California") => 1506,
    ("University of Nebraska", "University of Wisconsin") => 472,
    ("University of Southern California", "University of Wisconsin") => 1970,
    }
}
